# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server/grpc/voice_stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'server/grpc/voice_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eserver/grpc/voice_stream.proto\x12\x0c\x61i.inference\"\x07\n\x05\x45mpty\"6\n\x10QuestionResponse\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x10\n\x08topic_id\x18\x02 \x01(\t\"G\n\x0cRadioRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x13\n\x0b\x61nswer_text\x18\x03 \x01(\t\"3\n\rRadioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0e\n\x06script\x18\x02 \x01(\t\"a\n\x0cVoiceRequest\x12-\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1b.ai.inference.SessionConfigH\x00\x12\x17\n\raudio_content\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\"L\n\rSessionConfig\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x15\n\rlanguage_code\x18\x03 \x01(\t\"s\n\rVoiceResponse\x12\x16\n\x0c\x61udio_output\x18\x01 \x01(\x0cH\x00\x12\x14\n\ntranscript\x18\x02 \x01(\tH\x00\x12\x15\n\x0b\x61i_response\x18\x03 \x01(\tH\x00\x12\x12\n\x08is_final\x18\x04 \x01(\x08H\x00\x42\t\n\x07payload2\xad\x01\n\x11VoiceConversation\x12G\n\x10GetDailyQuestion\x12\x13.ai.inference.Empty\x1a\x1e.ai.inference.QuestionResponse\x12O\n\x14GenerateRadioContent\x12\x1a.ai.inference.RadioRequest\x1a\x1b.ai.inference.RadioResponseB*\n\x14\x63om.haruanbu.ai.grpcB\x10VoiceStreamProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.grpc.voice_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.haruanbu.ai.grpcB\020VoiceStreamProtoP\001'
  _globals['_EMPTY']._serialized_start=48
  _globals['_EMPTY']._serialized_end=55
  _globals['_QUESTIONRESPONSE']._serialized_start=57
  _globals['_QUESTIONRESPONSE']._serialized_end=111
  _globals['_RADIOREQUEST']._serialized_start=113
  _globals['_RADIOREQUEST']._serialized_end=184
  _globals['_RADIORESPONSE']._serialized_start=186
  _globals['_RADIORESPONSE']._serialized_end=237
  _globals['_VOICEREQUEST']._serialized_start=239
  _globals['_VOICEREQUEST']._serialized_end=336
  _globals['_SESSIONCONFIG']._serialized_start=338
  _globals['_SESSIONCONFIG']._serialized_end=414
  _globals['_VOICERESPONSE']._serialized_start=416
  _globals['_VOICERESPONSE']._serialized_end=531
  _globals['_VOICECONVERSATION']._serialized_start=534
  _globals['_VOICECONVERSATION']._serialized_end=707
# @@protoc_insertion_point(module_scope)
