# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from server.grpc import voice_stream_pb2 as server_dot_grpc_dot_voice__stream__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in server/grpc/voice_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceConversationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDailyQuestion = channel.unary_unary(
                '/ai.inference.VoiceConversation/GetDailyQuestion',
                request_serializer=server_dot_grpc_dot_voice__stream__pb2.Empty.SerializeToString,
                response_deserializer=server_dot_grpc_dot_voice__stream__pb2.QuestionResponse.FromString,
                _registered_method=True)
        self.GenerateRadioContent = channel.unary_unary(
                '/ai.inference.VoiceConversation/GenerateRadioContent',
                request_serializer=server_dot_grpc_dot_voice__stream__pb2.RadioRequest.SerializeToString,
                response_deserializer=server_dot_grpc_dot_voice__stream__pb2.RadioResponse.FromString,
                _registered_method=True)


class VoiceConversationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDailyQuestion(self, request, context):
        """양방향 스트리밍: 실시간 음성 데이터를 주고받음
        데일리 질문 생성 (LLM)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRadioContent(self, request, context):
        """라디오 콘텐츠 생성 (LLM + TTS)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceConversationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDailyQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailyQuestion,
                    request_deserializer=server_dot_grpc_dot_voice__stream__pb2.Empty.FromString,
                    response_serializer=server_dot_grpc_dot_voice__stream__pb2.QuestionResponse.SerializeToString,
            ),
            'GenerateRadioContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRadioContent,
                    request_deserializer=server_dot_grpc_dot_voice__stream__pb2.RadioRequest.FromString,
                    response_serializer=server_dot_grpc_dot_voice__stream__pb2.RadioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.inference.VoiceConversation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.inference.VoiceConversation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceConversation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDailyQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.inference.VoiceConversation/GetDailyQuestion',
            server_dot_grpc_dot_voice__stream__pb2.Empty.SerializeToString,
            server_dot_grpc_dot_voice__stream__pb2.QuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateRadioContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.inference.VoiceConversation/GenerateRadioContent',
            server_dot_grpc_dot_voice__stream__pb2.RadioRequest.SerializeToString,
            server_dot_grpc_dot_voice__stream__pb2.RadioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
